### ISSUE TITLE
generate_session now fails

### ISSUE THREAD

**Issue by codilau** [iSarabjitDhiman/TweeterPy#16]
This is not a guest_session

```python
Traceback (most recent call last):
  File ".../python3.10/site-packages/tweeterpy/request_util.py", line 22, in make_request
    if "json" in response.headers["Content-Type"]:
  File ".../python3.10/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../test_twitterPy.py", line 20, in <module>
    twitter_api = TweeterPy()
  File ".../python3.10/site-packages/tweeterpy/tweeterpy.py", line 19, in __init__
    self.generate_session()
  File ".../python3.10/site-packages/tweeterpy/tweeterpy.py", line 128, in generate_session
    make_request(Path.BASE_URL, session=self.session)
  File ".../python3.10/site-packages/tweeterpy/request_util.py", line 35, in make_request
    if api_limit_stats.get('rate_limit_exhausted'):
AttributeError: 'NoneType' object has no attribute 'get'
```

UPDATE:
It has recovered, but it's a bad sign that something is about to change.

**Comment by iSarabjitDhiman** [comment]
So it's working now ? Yeah there might be a sign that twitter is about to make changes, or maybe it was some issues with headers. As I noticed the script was unable to get a response. Keep me updated if you notice anything weird. Thanks
