### ISSUE TITLE
Couldn't find guest token!

### ISSUE THREAD

**Issue by datastd-dev** [iSarabjitDhiman/TweeterPy#58]
Hi, 

Code was working yesterday but I received error below today. Could someone help?

```python
2024-05-17 08:54:35,974 [INFO] :: NumExpr defaulting to 8 threads.
2024-05-17 08:54:37,956 [ERROR] :: Couldn't find guest token
2024-05-17 08:54:37,957 [ERROR] :: Couldn't generate a new session.
Couldn't find guest token
Traceback (most recent call last):
  File ".....python3.11/site-packages/tweeterpy/tweeterpy.py", line 159, in generate_session
    Path.GUEST_TOKEN_URL, method="POST", session=self.session).get('guest_token', util.find_guest_token(home_page))
                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".............python3.11/site-packages/tweeterpy/util.py", line 89, in find_guest_token
    raise Exception("Couldn't find guest token")
Exception: Couldn't find guest token
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[1], line 9
      5 import pandas as pd
      6 from tweeterpy import config
----> 9 twitter = TweeterPy()
     10 config.UPDATE_API = False

File ......./python3.11/site-packages/tweeterpy/tweeterpy.py:29, in TweeterPy.__init__(self)
     27     disable_external_only = config.DISABLE_EXTERNAL_LOGS if not config.DISABLE_LOGS else False
     28     set_log_level(logging.ERROR, external_only=disable_external_only)
---> 29 self.generate_session()
     30 # update api endpoints
     31 try:

File "...........python3.11/site-packages/tweeterpy/tweeterpy.py:159, in TweeterPy.generate_session(self, auth_token)
    156 self.session.headers.update(util.generate_headers())
    157 home_page = make_request(Path.BASE_URL, session=self.session)
    158 guest_token = make_request(
--> 159     Path.GUEST_TOKEN_URL, method="POST", session=self.session).get('guest_token', util.find_guest_token(home_page))
    160 self.session.headers.update({'X-Guest-Token': guest_token})
    161 self.session.cookies.update({'gt': guest_token})

File /opt/anaconda3/lib/python3.11/site-packages/tweeterpy/util.py:89, in find_guest_token(page_source)
     87 guest_token_match = re.search(guest_token_regex,str(page_source))
     88 if not guest_token_match:
---> 89     raise Exception("Couldn't find guest token")
     90 guest_token = guest_token_match.group(1)
     91 return guest_token

Exception: Couldn't find guest token
```

**Comment by iSarabjitDhiman** [comment]
Hey @datastd-dev are you using multiple threads?

**Comment by datastd-dev** [comment]
Hiç, Yes, i guess as default. I did not change.Sarabjit Dhiman ***@***.***> şunları yazdı (17 May 2024 09:38):﻿
Hey @datastd-dev are you using multiple threads?

**Comment by iSarabjitDhiman** [comment]
Ahh I see, twitter just redirected all the old twitter.com URLs to x.com
![image](https://github.com/iSarabjitDhiman/TweeterPy/assets/96009601/bb29c8b9-d4a6-42ef-98b0-55127c578c77)

Fixing soon.

**Comment by datastd-dev** [comment]
I took same error although uninstalling and installing again. what should i do?

**Comment by iSarabjitDhiman** [comment]
@datastd-dev 

run this command
```python
pip install -U tweeterpy
```

**Comment by datastd-dev** [comment]
solved. thanks a lot.

**Comment by New-dev0** [comment]
I am still getting this error 

", line 162, in generate_session
    Path.GUEST_TOKEN_URL, method="POST", session=self.session).get('guest_token', util.find_guest_token(home_page))
  File "_Python310\site-packages\tweeterpy\util.py", line 92, in find_guest_token
    raise Exception("Couldn't find guest token")        
Exception: Couldn't find guest token

**Comment by iSarabjitDhiman** [comment]
> I am still getting this error 
> 
> ", line 162, in generate_session
>     Path.GUEST_TOKEN_URL, method="POST", session=self.session).get('guest_token', util.find_guest_token(home_page))
>   File "_Python310\site-packages\tweeterpy\util.py", line 92, in find_guest_token
>     raise Exception("Couldn't find guest token")        
> Exception: Couldn't find guest token

Hey @New-dev0 
Make sure to update the package

```python

pip install -U tweeterpy

```
